version: "3.6"

services:
  db:
    restart: always
    image: postgres:12.1
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser
    ports:
      - "54320:5432"
