server:
  port: 8081

spring:
  application:
    name: cacheExample
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: testuser
    password: testuser
    url: jdbc:postgresql://127.0.0.1:54320/testdb?ApplicationName=${spring.application.name}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: cacheExamplePool
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 600000
      connection-timeout: 20000
      leak-detection-threshold: 0
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        generate-ddl: false
        ddl-auto: none
#        cache:
#          use_second_level_cache: true
#          use_query_cache: true
#          hazelcast:
#            use_native_client: true
#            native_client_address: 172.17.0.3:5701
#            native_client_group: dev
#            native_client_password: dev-pass

#          region:
#            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
        temp:
          use_jdbc_metadata_defaults: false

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
