version: "3.6"

services:
  db:
    restart: always
    image: postgres:12.1
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testuser
    ports:
      - "54320:5432"

  # hazelcast imdg
  hazelcast:
    restart: always
    image: hazelcast/hazelcast
    volumes:
      - ./hazelcast:/configFolder
    environment:
      - MANCENTER_URL=http://mancenter:8080/hazelcast-mancenter
      - JAVA_OPTS=-Dhazelcast.diagnostics.enabled=true -Dhazelcast.config=/configFolder/hazelcast.xml -Dgroup.name=hz-compose -Dgroup.password=s3crEt
    links:
      - "management-center:mancenter"

  #management center
  management-center:
    restart: always
    image: hazelcast/management-center
    # persisting mancenter users db folder to local disk
    volumes:
      - ./hazelcast-mancenter:/hazelcast-mancenter
    environment:
      - MANCENTER_DATA=/hazelcast-mancenter
      # enable REST interface on management center
      # http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Clustered_REST_via_Management_Center.html
      - JAVA_OPTS=-Dhazelcast.mc.rest.enabled=true --illegal-access=warn --add-modules java.se --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
    ports:
      - 8080:8080
